### PR TITLE
Update one-jar-boot 0.97 to version 0.97.1

### PR DESCRIPTION
**Pull request by joschi**
There is a more recent version of OneJar available at http://sourceforge.net/projects/one-jar/files/one-jar/one-jar-0.97.1/ than the one packaged with the gradle-one-jar plugin.

Unfortunately it has the same filename as the old JAR file but is more recent (2012-08-15) than the one packaged with this Gradle plugin (2011-05-05).

### CODE REVIEW

**Comment by rholder** [comment]
That's a good catch. The ads all over SourceForge these days likely had me distracted when I went to fetch the latest release :). I'll roll out an update soon.

**Comment by rholder** [comment]
Hmm, this version of OneJar appears to be a little more verbose at logging boot information on startup:

```
[Boot] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@19cd6b6)
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
```

I'll put a note somewhere about adding -Done-jar.silent=true as a JVM parameter to quiet it down.

**Comment by joschi** [comment]
Unfortunately it's not that easy to find out what changed between One JAR 0.97 and 0.97.1. I had also asked Simon, the developer of One JAR, about this in the SourceForge forum for the project ([thread](http://sourceforge.net/projects/one-jar/forums/forum/380843/topic/6719379)) and created a diff of both versions ([gist](https://gist.github.com/joschi/4994511)).

Just in case you're interested in the details. ;)

**Comment by rholder** [comment]
Ah, that could be quite useful, thanks.

**Comment by mal-appear** [comment]
Is it possible to add JVM param-Done-jar.silent=true in the jar file created ? so user don't have to specify on the command line ?

**Comment by rholder** [comment]
I've tacked this stub script onto the front of the final generated archive in some of my builds to get around that annoying logging: 

``` bash
#!/bin/sh

# Adapted stub script from https://coderwall.com/p/ssuaxa

THIS_STUB=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && THIS_STUB="./$0"
java=java
if test -n "$JAVA_HOME"; then
java="$JAVA_HOME/bin/java"
fi
exec "$java" -Done-jar.silent=true $java_args -jar $THIS_STUB "$@"
exit 1
```

It basically just adds that parameter and maintains consistent error return codes on *nix systems. Check out the post [here](https://coderwall.com/p/ssuaxa) for more details on how/why that works. Some form of automating the appending of specific JAVA_OPTS might be a nice feature to add to this plugin.

**Pull request merged**
